apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-svc"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.label }}
  ports:
    - port: 5432
      targetPort: 5432
