name: Deploy the http-server
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to machine
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pull Image from DockerHub
        run: docker pull tsmukesh51/dpl-dockr-http:latest || true
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ./dpl-dockr
          file: ./dpl-dockr/dockerfile/http-server.dockerfile
          push: true
          cache-from: type=registry,ref=tsmukesh51/dpl-dockr-http:latest
          tags: tsmukesh51/dpl-dockr-http:${{ github.sha }},tsmukesh51/dpl-dockr-http:latest
          cache-to: type=gha,mode=max
      - name: Deploy on VM
        run: 'echo "hello world"'
