name: Deploy the http-server
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to machine
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pull Image from DockerHub
        run: docker pull tsmukesh51/dpl-dockr-http:latest || true
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: ./dpl-dockr
          file: ./dpl-dockr/dockerfile/http-server.dockerfile
          push: true
          cache-from: type=registry,ref=tsmukesh51/dpl-dockr-http:latest
          tags: tsmukesh51/dpl-dockr-http:${{ github.sha }},tsmukesh51/dpl-dockr-http:latest
          cache-to: type=gha,mode=max
      - name: Deploy on VM
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.VULTR_MYTRYING_FINGERPRINT }}" &> ~/.ssh/known_hosts
          echo "${{ secrets.SDWMUKESH_SSH_PRIVKEY }}" &> ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key
          ssh -i ~/.ssh/ssh_key root@${{ vars.VULTR_MYTRYING_IPADD }} << EOF
          echo "Pulling image"
          docker pull tsmukesh51/dpl-dockr-http:${{ github.sha }} || { echo "Pull failed"; exit 1; }
          echo "Container Stopped"
          docker stop tsmukesh51/dpl-dockr-http || true
          echo "Container Removed"
          docker rm tsmukesh51/dpl-dockr-http || true
          echo "Running New Container ${{ secrets.NT_DATABASE_URL }}"
          docker run -e DATABASE_URL="${{ secrets.NT_DATABASE_URL }}" -p 3000:3000 -d --name tsmukesh51-dpl-dockr-http:${{ github.sha }} || { echo "Run failed"; exit 1; }
          EOF
